In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
x = np.array([2,3,5,1,2,4])
print(x)
print('total element =>' ,x.size)
print('dimension wise element=>',x.shape)
print('dimension count',x.ndim)

[2 3 5 1 2 4]
total element => 6
dimension wise element=> (6,)
dimension count 1


In [7]:
y = np.array([[2,3,5],[1,2,4]])
print(y)
print('total element =>' ,y.size)
print('dimension wise element=>',y.shape)
print('dimension count',y.ndim)

[[2 3 5]
 [1 2 4]]
total element => 6
dimension wise element=> (2, 3)
dimension count 2


In [9]:
x = [1,2,3,4,5]
z = np.array([[x,x,x],[x,x,x],[x,x,x]])
print('shape',z.shape)
print(z)

shape (3, 3, 5)
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [19]:
d = np.arange(-10,11,.5)
d.shape

(42,)

In [20]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [21]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [25]:
a = np.linspace(1,1000,11)
a

array([   1. ,  100.9,  200.8,  300.7,  400.6,  500.5,  600.4,  700.3,
        800.2,  900.1, 1000. ])

In [26]:
np.random.randint(1,5,(10,10))

array([[2, 2, 3, 1, 2, 4, 4, 1, 4, 3],
       [3, 1, 1, 1, 3, 4, 1, 4, 3, 1],
       [2, 1, 2, 3, 3, 2, 4, 3, 4, 4],
       [3, 1, 3, 1, 1, 2, 3, 2, 3, 1],
       [4, 4, 1, 4, 1, 4, 1, 2, 4, 3],
       [4, 2, 1, 4, 3, 3, 2, 4, 4, 1],
       [4, 1, 4, 2, 3, 1, 2, 3, 1, 3],
       [2, 2, 4, 3, 3, 4, 3, 1, 3, 3],
       [1, 3, 1, 3, 1, 4, 3, 4, 3, 2],
       [2, 1, 3, 2, 3, 2, 2, 3, 2, 4]])

In [28]:
d = np.random.randint(1,6,(10,10))
d

array([[5, 5, 4, 1, 4, 3, 1, 2, 4, 2],
       [1, 4, 2, 2, 1, 2, 4, 5, 2, 1],
       [3, 3, 1, 4, 1, 4, 2, 1, 2, 4],
       [5, 4, 4, 5, 2, 5, 5, 2, 3, 5],
       [4, 2, 3, 3, 1, 5, 1, 2, 1, 3],
       [1, 4, 4, 5, 2, 2, 1, 5, 1, 4],
       [4, 3, 1, 1, 2, 5, 2, 5, 2, 1],
       [5, 2, 3, 3, 5, 3, 2, 4, 4, 2],
       [4, 2, 2, 1, 3, 2, 3, 3, 2, 5],
       [5, 4, 3, 4, 2, 2, 5, 5, 2, 4]])

In [29]:
print(d)

[[5 5 4 1 4 3 1 2 4 2]
 [1 4 2 2 1 2 4 5 2 1]
 [3 3 1 4 1 4 2 1 2 4]
 [5 4 4 5 2 5 5 2 3 5]
 [4 2 3 3 1 5 1 2 1 3]
 [1 4 4 5 2 2 1 5 1 4]
 [4 3 1 1 2 5 2 5 2 1]
 [5 2 3 3 5 3 2 4 4 2]
 [4 2 2 1 3 2 3 3 2 5]
 [5 4 3 4 2 2 5 5 2 4]]


In [30]:
d[-1]

array([5, 4, 3, 4, 2, 2, 5, 5, 2, 4])

In [36]:
d[0,0]#d[0][0]

5

In [32]:
d[3,5]

5

In [33]:
d[:, -3]

array([2, 5, 1, 2, 2, 5, 5, 4, 3, 5])

In [34]:
d[:5,2] # first five rows of column idx 2

array([4, 2, 1, 4, 3])

In [37]:
d[:5,:5]

array([[5, 5, 4, 1, 4],
       [1, 4, 2, 2, 1],
       [3, 3, 1, 4, 1],
       [5, 4, 4, 5, 2],
       [4, 2, 3, 3, 1]])

In [38]:
x = np.random.randint(1,10, (3,3))
y = np.random.randint(1,10, (3,3))
print(x,'\n',y)

[[5 8 1]
 [3 1 8]
 [8 2 4]] 
 [[2 4 2]
 [4 8 6]
 [5 7 3]]


In [39]:
x+y

array([[ 7, 12,  3],
       [ 7,  9, 14],
       [13,  9,  7]])

In [40]:
x - y

array([[ 3,  4, -1],
       [-1, -7,  2],
       [ 3, -5,  1]])

In [41]:
x -10

array([[-5, -2, -9],
       [-7, -9, -2],
       [-2, -8, -6]])

In [42]:
x * 10

array([[50, 80, 10],
       [30, 10, 80],
       [80, 20, 40]])

In [43]:
np.dot(x,y)

array([[47, 91, 61],
       [50, 76, 36],
       [44, 76, 40]])

In [44]:
np.matmul(x,y)

array([[47, 91, 61],
       [50, 76, 36],
       [44, 76, 40]])

In [45]:
np.multiply(x,y)

array([[10, 32,  2],
       [12,  8, 48],
       [40, 14, 12]])

In [46]:
x * y

array([[10, 32,  2],
       [12,  8, 48],
       [40, 14, 12]])

In [47]:
np.cross(x,y)

array([[ 12,  -8,   4],
       [-58,  14,  20],
       [-22,  -4,  46]])

In [48]:
np.hstack([x,y])

array([[5, 8, 1, 2, 4, 2],
       [3, 1, 8, 4, 8, 6],
       [8, 2, 4, 5, 7, 3]])

In [49]:
np.vstack([x,y])

array([[5, 8, 1],
       [3, 1, 8],
       [8, 2, 4],
       [2, 4, 2],
       [4, 8, 6],
       [5, 7, 3]])

In [51]:
np.append(x,y,axis=0)

array([[5, 8, 1],
       [3, 1, 8],
       [8, 2, 4],
       [2, 4, 2],
       [4, 8, 6],
       [5, 7, 3]])

In [53]:
x.max(axis=0)

array([8, 8, 8])

In [54]:
x.min(axis=1)

array([1, 1, 2])

In [55]:
x.flatten()

array([5, 8, 1, 3, 1, 8, 8, 2, 4])

In [56]:
d

array([[5, 5, 4, 1, 4, 3, 1, 2, 4, 2],
       [1, 4, 2, 2, 1, 2, 4, 5, 2, 1],
       [3, 3, 1, 4, 1, 4, 2, 1, 2, 4],
       [5, 4, 4, 5, 2, 5, 5, 2, 3, 5],
       [4, 2, 3, 3, 1, 5, 1, 2, 1, 3],
       [1, 4, 4, 5, 2, 2, 1, 5, 1, 4],
       [4, 3, 1, 1, 2, 5, 2, 5, 2, 1],
       [5, 2, 3, 3, 5, 3, 2, 4, 4, 2],
       [4, 2, 2, 1, 3, 2, 3, 3, 2, 5],
       [5, 4, 3, 4, 2, 2, 5, 5, 2, 4]])

In [57]:
d[d > 3]

array([5, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 5, 4, 4, 5, 5, 5, 5, 4, 5, 4, 4,
       5, 5, 4, 4, 5, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 5, 5, 4])

In [58]:
d[d==1]# give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])